name: flutter_resas_api_hands_on
description: This is a repository for hands-on exercises with the RESAS API.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:

flutter:
  uses-material-design: true
